"use client"

import { motion } from "framer-motion"

export function Footer() {
  return (
    <footer className="py-16 px-4 border-t border-border/50">
      <div className="max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="flex flex-col items-center gap-8"
        >
          <div className="flex flex-col md:flex-row items-center justify-between gap-6 w-full">
            <div className="text-center md:text-left">
              <p className="text-muted-foreground">Built for the Vibe ecosystem</p>
            </div>

            <div className="flex flex-wrap items-center justify-center gap-8">
              <a href="#tools" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                Tools
              </a>
              <a href="#resources" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                Resources
              </a>
              <a href="#" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                Contact
              </a>
            </div>
          </div>

          {/* Terms and Conditions */}
          <div className="text-center max-w-3xl">
            <p className="text-xs text-slate-500 leading-relaxed">
              * If you find any mistakes or inaccuracies, please contact the owner and it will be corrected accordingly. 
              We do not take any responsibility for the content generated by AI. All information is provided for informational purposes only.
            </p>
          </div>
        </motion.div>
      </div>
    </footer>
  )
}
